import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: { absolute: "Privacy Policy · Readup" },
  description: "How Readup collects, uses, and protects your personal information.",
};

const sections = [
  { id: "information", label: "Information we collect" },
  { id: "use", label: "How we use information" },
  { id: "sharing", label: "How information is shared" },
  { id: "retention", label: "Retention and security" },
  { id: "choices", label: "Your choices and rights" },
  { id: "children", label: "Children’s privacy" },
  { id: "changes", label: "Changes to this policy" },
  { id: "contact", label: "Contact us" },
] as const;

export default function PrivacyPage() {
  return (
    <main className="min-h-full bg-[#fbfaf5] text-[#1a2420]">
      <header className="border-b border-[#dde5df] bg-white/90">
        <div className="mx-auto flex max-w-5xl items-center px-6 py-5 sm:px-10">
          <Image src="/readup-logo.svg" alt="Readup" width={92} height={25} priority />
        </div>
      </header>

      <div className="mx-auto grid max-w-5xl gap-12 px-6 py-12 sm:px-10 sm:py-16 lg:grid-cols-[220px_minmax(0,1fr)] lg:gap-16">
        <aside className="hidden lg:block">
          <nav aria-label="Privacy policy sections" className="sticky top-8">
            <p className="mb-4 text-xs font-semibold tracking-[0.14em] text-[#66736d] uppercase">
              On this page
            </p>
            <ul className="space-y-3 border-l border-[#ccd8d0] pl-4 text-sm text-[#52615a]">
              {sections.map((section) => (
                <li key={section.id}>
                  <a className="transition-colors hover:text-[#047857]" href={`#${section.id}`}>
                    {section.label}
                  </a>
                </li>
              ))}
            </ul>
          </nav>
        </aside>

        <article className="min-w-0">
          <div className="border-b border-[#ccd8d0] pb-10">
            <p className="mb-3 text-sm font-semibold text-[#047857]">Readup</p>
            <h1 className="text-4xl font-extrabold tracking-[-0.04em] sm:text-5xl">
              Privacy Policy
            </h1>
            <p className="mt-5 max-w-2xl text-lg leading-8 text-[#52615a]">
              This policy explains what information Readup collects, why we use it, and the
              choices available to you when you use the Readup mobile application and related
              services.
            </p>
            <p className="mt-5 text-sm text-[#66736d]">
              Effective date: August 5, 2026
            </p>
          </div>

          <div className="space-y-12 pt-10 text-[16px] leading-7 text-[#35443d]">
            <PolicySection id="information" title="1. Information we collect">
              <p>We collect information that you provide or create while using Readup:</p>
              <ul>
                <li>
                  <strong>Account information:</strong> your email address, name, authentication
                  provider, and account identifiers.
                </li>
                <li>
                  <strong>Profile and preferences:</strong> reading interests and goals, interface
                  settings, and notification preferences.
                </li>
                <li>
                  <strong>Reading activity:</strong> books saved to your library, reading progress,
                  reading history and streaks, quotes you save, searches, quiz attempts, and
                  achievements.
                </li>
                <li>
                  <strong>Service information:</strong> basic technical data needed to operate and
                  secure the service, such as device, browser, IP address, and diagnostic or access
                  logs generated by our service providers.
                </li>
              </ul>
              <p>
                If you sign in with Apple, Google, or another authentication provider, we receive
                the account details that provider makes available according to your settings with
                that provider.
              </p>
            </PolicySection>

            <PolicySection id="use" title="2. How we use information">
              <p>We use your information to:</p>
              <ul>
                <li>create and maintain your account;</li>
                <li>sync your library, progress, preferences, and reading activity;</li>
                <li>personalize content and improve the reading experience;</li>
                <li>provide support and send service-related communications;</li>
                <li>protect Readup, prevent abuse, and troubleshoot technical issues; and</li>
                <li>comply with legal obligations and enforce our rights.</li>
              </ul>
              <p>We do not sell your personal information or use it for third-party advertising.</p>
            </PolicySection>

            <PolicySection id="sharing" title="3. How information is shared">
              <p>We may share information only in the following circumstances:</p>
              <ul>
                <li>
                  <strong>Service providers:</strong> with providers that host infrastructure,
                  store data, authenticate users, deliver app functionality, or help us maintain
                  security. They may process information only to provide services to Readup.
                </li>
                <li>
                  <strong>Legal and safety reasons:</strong> when reasonably necessary to comply
                  with law, respond to lawful requests, protect users, or defend our legal rights.
                </li>
                <li>
                  <strong>Business transfers:</strong> as part of a merger, acquisition,
                  financing, reorganization, or sale of assets, subject to appropriate safeguards.
                </li>
                <li>
                  <strong>With your direction:</strong> when you ask us to share information or
                  give us consent.
                </li>
              </ul>
              <p>
                Our providers may process information in countries other than the country where
                you live. Where required, we use appropriate safeguards for these transfers.
              </p>
            </PolicySection>

            <PolicySection id="retention" title="4. Retention and security">
              <p>
                We keep personal information for as long as your account is active or as needed to
                provide Readup, meet legal requirements, resolve disputes, and protect the service.
                When information is no longer needed, we delete or anonymize it where reasonably
                practicable.
              </p>
              <p>
                We use reasonable administrative, technical, and organizational safeguards to
                protect your information. No system is completely secure, so we cannot guarantee
                absolute security.
              </p>
            </PolicySection>

            <PolicySection id="choices" title="5. Your choices and rights">
              <p>
                Depending on where you live, you may have the right to access, correct, export,
                restrict, object to the processing of, or delete your personal information. You
                can update certain profile and notification settings in the app. You can also
                request account deletion from the app’s settings.
              </p>
              <p>
                You may contact us to exercise another privacy right. We may need to verify your
                identity before completing a request. You may also have the right to complain to
                your local data protection authority.
              </p>
            </PolicySection>

            <PolicySection id="children" title="6. Children’s privacy">
              <p>
                Readup is not directed to children under 13, or a higher minimum age where required
                by local law. We do not knowingly collect personal information from children below
                that age. If you believe a child has provided us with personal information, please
                contact us so we can take appropriate action.
              </p>
            </PolicySection>

            <PolicySection id="changes" title="7. Changes to this policy">
              <p>
                We may update this policy as Readup or applicable law changes. We will post the
                updated policy here and revise the effective date. If a change materially affects
                your rights, we will provide additional notice when required.
              </p>
            </PolicySection>

            <PolicySection id="contact" title="8. Contact us">
              <p>
                For privacy questions or requests, email us at{" "}
                <a className="font-semibold text-[#047857] underline underline-offset-4" href="mailto:privacy@readup.kz">
                  privacy@readup.kz
                </a>
                .
              </p>
            </PolicySection>
          </div>
        </article>
      </div>
    </main>
  );
}

function PolicySection({
  id,
  title,
  children,
}: Readonly<{
  id: string;
  title: string;
  children: React.ReactNode;
}>) {
  return (
    <section id={id} className="scroll-mt-8 space-y-4 [&_li]:pl-2 [&_strong]:font-semibold [&_ul]:list-disc [&_ul]:space-y-2 [&_ul]:pl-6">
      <h2 className="text-2xl font-bold tracking-[-0.025em] text-[#1a2420]">{title}</h2>
      {children}
    </section>
  );
}
